### ISSUE TITLE
Use codecov GitHub App integration 

### ISSUE THREAD

**Issue by Mariatta** [gidgethub/gidgethub#196]
On this PR, there's a message from Codecov: (https://github.com/brettcannon/gidgethub/pull/194#issuecomment-1525772352)
> 📣 This organization is not using Codecov’s [GitHub App Integration](https://github.com/apps/codecov). We recommend you install it so Codecov can continue to function properly for your repositories. [Learn more](https://about.codecov.io/blog/codecov-is-updating-its-github-integration/?utm_medium=referral&utm_source=github&utm_content=comment&utm_campaign=pr+comments&utm_term=Brett+Cannon)

So let's do that? Or use another alternative.

**Comment by brettcannon** [comment]
I guess the question is how much do we care about a specific code coverage target, and do we care about producing browsable results beyond an ASCII table from coverage.py in CI?

I'm personally okay with either solution.

**Comment by Mariatta** [comment]
I still prefer being able to see HTML coverage output, however as an experienced contributor, I know how to do it locally so I don't need it on the CI.

**Comment by brettcannon** [comment]
Since this is still under my personal account I think I would have to install Codecov for my entire personal account which I would like to avoid.

We can also move this project to its own org account where you are equal owner and we can set up whatever we want.

**Comment by Mariatta** [comment]
I'm ok with moving to an org account.

**Comment by brettcannon** [comment]
Anything I should watch out for before making a gidgethub org and moving this repo over to it? Nothing comes to mind, but I haven't ever done this either, so I'm not sure what I would have to watch out for breaking. 😅

**Comment by Mariatta** [comment]
Maybe read up the docs first to understand what gets transferred. (Looks like pretty much everything, and if people try to hit the old URL, GitHub will redirect it to the new org URL)

The other we may need to do is to re-wire readthedocs to the org repo.

**Comment by Mariatta** [comment]
This note sticks out to me:

```
: If you create a new repository under your account in the future, do not reuse the original name of the transferred repository. If you do, redirects to the transferred repository will no longer work.
```

For you I think it means you can't fork gidgethub from the org repo to your personal account 🤔, or it would break the redirect 😅

**Comment by brettcannon** [comment]
> For you I think it means you can't fork gidgethub from the org repo to your personal account

That's fine. I can just do branches in the main repo.

**Comment by brettcannon** [comment]
Moved! You should have an invite to be an owner of the new org.

**Comment by Mariatta** [comment]
Got it. Thanks!

**Comment by Mariatta** [comment]
I've installed codecov app to the gidgethub/gidgethub repository.
